import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.butchery": "الملحمة",
    "nav.restaurant": "المطعم",
    "nav.catering": "التموين",
    "nav.menu": "القائمة",
    "nav.recipes": "الوصفات",
    "nav.blog": "المدونة",
    "nav.about": "من نحن",
    "nav.contact": "تواصل معنا",
    "nav.offers": "العروض",
    "nav.viewAll": "عرض الكل",
    
    // Shop Categories
    "shop.beef": "لحوم بقري",
    "shop.lamb": "لحوم غنم",
    "shop.chicken": "دجاج",
    "shop.readyToGrill": "جاهز للشوي",
    "shop.specialCuts": "قطوعات خاصة",
    "shop.boxes": "بوكسات خاصة",
    "shop.sections": "الأقسام",
    "shop.showing": "عرض",
    "shop.products": "منتج",
    "shop.noProducts": "لا توجد منتجات في هذا القسم",
    "shop.discoverCollection": "اكتشف مجموعتنا المختارة من اللحوم الطازجة والحلال",
    
    // Catering Services
    "catering.corporate": "تموين شركات",
    "catering.wedding": "تموين أعراس",
    "catering.events": "تموين مناسبات",
    "catering.bbq": "تموين شوي",
    "catering.aboutService": "عن خدمة",
    "catering.serviceFeatures": "مميزات الخدمة",
    "catering.serviceIntro": "نقدم في ملحمة السرايا خدمات التموين بأعلى معايير الجودة والاحترافية. نحرص على تقديم أجود أنواع اللحوم الطازجة مع طاقم عمل متخصص لضمان نجاح مناسبتك.",
    "catering.serviceIntroEn": "At Al Saraya Butchery, we provide catering services with the highest quality and professionalism. We ensure the finest fresh meats with specialized staff to guarantee your event's success.",
    "catering.getQuote": "اطلب عرض سعر",
    "catering.ourWorks": "من أعمالنا",
    "catering.haveEvent": "هل لديك مناسبة قريبة؟",
    "catering.eventDescription": "تواصل معنا الآن للحصول على عرض سعر مخصص لمناسبتك. فريقنا جاهز لمساعدتك في تحقيق مناسبة لا تُنسى.",
    "catering.contactPage": "صفحة التواصل",
    "catering.serviceNotFound": "الخدمة غير موجودة",
    "catering.serviceNotFoundDesc": "عذرًا، لم نتمكن من العثور على هذه الخدمة",
    "catering.mainDescription": "نقدم خدمات تموين متكاملة للمناسبات الخاصة والفعاليات باستخدام أجود أنواع اللحوم",
    "catering.learnMore": "اعرف المزيد",
    
    // Restaurant Categories
    "restaurant.bbq": "مشاوي",
    "restaurant.pottery": "فخاريات",
    "restaurant.sandwiches": "سندويشات",
    "restaurant.fattat": "فتات وفول",
    "restaurant.shamyat": "شاميات",
    "restaurant.manakeesh": "مناقيش",
    "restaurant.appetizers": "مقبلات",
    "restaurant.salads": "سلطات",
    "restaurant.drinks": "مشروبات",
    "restaurant.menuSections": "أقسام القائمة",
    "restaurant.showAll": "عرض الكل",
    "restaurant.allItems": "جميع الأصناف",
    "restaurant.items": "صنف",
    "restaurant.readyToOrder": "جاهز للطلب؟ تواصل معنا الآن!",
    "restaurant.fastDelivery": "توصيل سريع لباب منزلك في أبوظبي",
    "restaurant.deliveryAvailable": "توصيل متوفر في أبوظبي",
    "restaurant.tagline": "في السرايا، الطبخة من القلب، والنكهة من الذاكرة",
    "restaurant.taglineEn": "At Al Saraya, cooking from the heart, flavor from memory",
    
    // Buttons & CTAs
    "cta.callUs": "اتصل بنا",
    "cta.orderNow": "اطلب الآن",
    "cta.whatsapp": "واتساب",
    "cta.learnMore": "اعرف المزيد",
    "cta.viewMenu": "عرض القائمة",
    "cta.viewAll": "عرض الكل",
    "cta.sendMessage": "إرسال الرسالة",
    "cta.startChat": "ابدأ المحادثة",
    "cta.orderWhatsapp": "اطلب واتساب",
    "cta.browseProducts": "تصفح جميع المنتجات",
    "cta.orderNowWhatsapp": "اطلب الآن عبر واتساب",
    "cta.getFreshMeat": "احصل على لحم طازج اليوم",
    "cta.browseMenu": "تصفح القائمة",
    "cta.learnMoreAbout": "اعرف المزيد عنا",
    "cta.exploreServices": "استكشف خدماتنا",
    "cta.getQuote": "اطلب عرض سعر",
    "cta.shopNow": "تسوق الآن",
    "cta.contactUs": "تواصل معنا",
    "cta.browseProductsPage": "تصفح المنتجات",
    "cta.buyNow": "اشترِ الآن",
    "cta.orderViaWhatsapp": "اطلب واتساب",
    "cta.shopIngredients": "تسوق المكونات",
    "cta.allRecipes": "جميع الوصفات",
    "cta.orderWhatsappNow": "اطلب عبر واتساب",
    
    // Header
    "header.title": "ملحمة السرايا",
    "header.subtitle": "Al Saraya Butchery",
    "header.searchPlaceholder": "ابحث عن المنتجات...",
    
    // Hero Section
    "hero.badge": "جودة لا مثيل لها منذ عام 2019",
    "hero.title": "ملحمة السرايا",
    "hero.subtitle": "حيث تبدأ جودة اللحم وتبدأ الثقة",
    "hero.description": "في ملحمة السرايا نقدم لحومًا طازجة مختارة بعناية، مقطّعة باحتراف، ومحضّرة لتناسب كل الأذواق — من المشاوي العائلية إلى الولائم والمناسبات الكبرى.",
    "hero.stats.years": "سنوات خبرة",
    "hero.stats.customers": "عميل سعيد",
    "hero.stats.halal": "لحوم حلال",
    
    // About Section & Page
    "about.tagline": "من نحن",
    "about.title": "قصة ملحمة السرايا",
    "about.description1": "ملحمة السرايا تأسست لتقديم لحوم طازجة وعالية الجودة تلبي ثقة عملائنا يومًا بعد يوم. نحن نفخر بكوننا الخيار الأول للعائلات والمطاعم الباحثة عن الجودة.",
    "about.description2": "نلتزم بأعلى معايير الذبح الحلال، النظافة، والاختيار الدقيق، لنضمن لك تجربة شراء مريحة وطعم لا يُنسى.",
    "about.experience": "سنة من التميز",
    "about.feature.halal": "ذبح حلال",
    "about.feature.halalDesc": "جميع لحومنا مذبوحة وفق الشريعة الإسلامية",
    "about.feature.fresh": "طازج يوميًا",
    "about.feature.freshDesc": "لحوم طازجة تصل إليك من المزرعة مباشرة",
    "about.feature.quality": "جودة مضمونة",
    "about.feature.qualityDesc": "أعلى معايير الجودة والنظافة في الصناعة",
    "about.feature.service": "خدمة مميزة",
    "about.feature.serviceDesc": "فريق محترف يضمن رضاك التام",
    "about.storyTagline": "قصتنا",
    "about.storyTitle": "رحلة التميز في عالم اللحوم",
    "about.storyP1": "تأسست ملحمة السرايا عام 2010 بهدف واضح: تقديم أجود أنواع اللحوم الطازجة والحلال لعملائنا في الإمارات العربية المتحدة.",
    "about.storyP2": "بدأنا كملحمة صغيرة بإدارة عائلية، واليوم نفخر بكوننا الوجهة المفضلة للعائلات والمطاعم الباحثة عن الجودة والثقة.",
    "about.storyP3": "نلتزم بأعلى معايير الذبح الحلال، النظافة، والاختيار الدقيق، لنضمن لك تجربة شراء مريحة وطعم لا يُنسى في كل مرة.",
    "about.storyP4": "فريقنا المتخصص يحرص على اختيار أفضل اللحوم المحلية والمستوردة، مقطّعة باحتراف وجاهزة لتلبية احتياجاتك.",
    "about.valuesTagline": "قيمنا",
    "about.valuesTitle": "ما يميزنا",
    "about.valuesDescription": "نلتزم بمجموعة من القيم التي تضمن لك أفضل تجربة مع كل تعامل",
    "about.value.halalSlaughter": "ذبح حلال",
    "about.value.halalSlaughterDesc": "جميع لحومنا مذبوحة وفق الشريعة الإسلامية على يد متخصصين",
    "about.value.freshDaily": "طازج يوميًا",
    "about.value.freshDailyDesc": "لحوم طازجة تصل إليك من المزرعة مباشرة كل يوم",
    "about.value.qualityGuaranteed": "جودة مضمونة",
    "about.value.qualityGuaranteedDesc": "أعلى معايير الجودة والنظافة في كل مرحلة",
    "about.value.excellentService": "خدمة مميزة",
    "about.value.excellentServiceDesc": "فريق محترف يضمن رضاك التام في كل تعامل",
    "about.value.longExperience": "خبرة طويلة",
    "about.value.longExperienceDesc": "أكثر من 14 عامًا من الخبرة في خدمة عملائنا",
    "about.value.fastDelivery": "توصيل سريع",
    "about.value.fastDeliveryDesc": "خدمة توصيل سريعة لضمان وصول اللحم طازجًا",
    "about.teamTagline": "فريقنا",
    "about.teamTitle": "فريق ملحمة السرايا",
    "about.teamDescription": "نفخر بفريقنا المحترف الذي يضمن لك أفضل جودة وخدمة",
    "about.butcheryTeam": "فريق الملحمة",
    "about.butcheryTeamDesc": "جزارون وطهاة محترفون بخبرة طويلة في تقديم أجود اللحوم",
    "about.deliveryTeam": "فريق التوصيل",
    "about.deliveryTeamDesc": "فريق توصيل متخصص يضمن وصول طلبك طازجًا وفي الوقت المحدد",
    "about.successTeam": "فريق النجاح",
    "about.generalManager": "المدير العام والمشرف",
    "about.managerDesc": "الواجهة الإعلانية للملحمة ومشرف على إنشائها منذ البداية",
    "about.socialMediaManager": "Social Media & Web Manager",
    "about.socialMediaManagerDesc": "مسؤول التسويق الرقمي وتطوير الموقع الإلكتروني",
    "about.joinFamily": "انضم لعائلة السرايا",
    "about.alwaysAtService": "نحن دائمًا في خدمتك. تواصل معنا للطلبات أو الاستفسارات",
    "about.stats.years": "سنة خبرة",
    "about.stats.customers": "عميل سعيد",
    "about.stats.events": "مناسبة سنويًا",
    "about.stats.halal": "لحوم حلال",
    
    // Products Section
    "products.tagline": "منتجاتنا",
    "products.title": "منتجات مميزة",
    "products.description": "اكتشف مجموعتنا المختارة من اللحوم الطازجة والحلال، المجهزة يوميًا بأعلى معايير الجودة.",
    "products.new": "جديد",
    "products.sale": "عرض",
    "products.currency": "د.إ",
    
    // Product Names
    "product.ribEye": "ستيك ريب آي",
    "product.ribEyeDesc": "قطعة ريب آي فاخرة مع توزيع مثالي للدهون",
    "product.beefKebab": "كباب لحم بقري",
    "product.beefKebabDesc": "كباب لحم بقري طازج مع البهارات الشامية",
    "product.lambRibs": "ريش غنم",
    "product.lambRibsDesc": "ريش غنم طرية متبلة بخلطة خاصة",
    "product.chickenShawarma": "شاورما دجاج جاهزة",
    "product.chickenShawarmaDesc": "شاورما دجاج متبلة وجاهزة للشوي",
    "product.groundBeef": "لحم مفروم بقري",
    "product.groundBeefDesc": "لحم مفروم طازج للكباب والكفتة",
    "product.familyBBQ": "بوكس مشاوي عائلي",
    "product.familyBBQDesc": "تشكيلة متنوعة من اللحوم للعائلة",
    
    // Testimonials Section
    "testimonials.tagline": "آراء العملاء",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "testimonials.description": "ثقة عملائنا هي رأس مالنا الحقيقي، وتجربتهم معنا هي دليل جودة ما نقدّمه.",
    
    // Testimonial Content
    "testimonial.1.name": "أحمد محمد",
    "testimonial.1.role": "عميل منتظم",
    "testimonial.1.content": "أفضل ملحمة في دبي! اللحم دائمًا طازج وجودة القطوعات ممتازة. خدمة التوصيل سريعة والتعامل راقي جدًا.",
    "testimonial.2.name": "سارة العلي",
    "testimonial.2.role": "صاحبة مطعم",
    "testimonial.2.content": "نتعامل مع ملحمة السرايا منذ 3 سنوات لمطعمنا. الجودة ثابتة والأسعار منافسة. شريك موثوق لعملنا.",
    "testimonial.3.name": "خالد الحمادي",
    "testimonial.3.role": "محب للشوي",
    "testimonial.3.content": "تجربة رائعة! طلبت بوكس المشاوي لحفلة العائلة وكان الجميع سعيدًا بجودة اللحم والتتبيلة الشامية الأصيلة.",
    "testimonial.4.name": "فاطمة الشامسي",
    "testimonial.4.role": "ربة منزل",
    "testimonial.4.content": "خدمة التموين في عزيمة رمضان كانت مثالية! شكرًا لفريق السرايا على الاحترافية والجودة.",
    
    // Catering Section
    "catering.tagline": "خدمات التموين",
    "catering.title": "خدمات التموين والمناسبات",
    "catering.description": "تقدّم ملحمة السرايا خدمات تموين متكاملة للمناسبات الخاصة، العزائم، الحفلات، والفعاليات، باستخدام أجود أنواع اللحوم وتحضير احترافي.",
    "catering.service.wedding": "تموين أعراس ومناسبات",
    "catering.service.weddingDesc": "خدمات تموين متكاملة للأعراس والمناسبات الخاصة بأجود أنواع اللحوم",
    "catering.service.bbq": "تموين حفلات شوي",
    "catering.service.bbqDesc": "خدمة شوي احترافية في موقعك مع تجهيز كامل وطاقم متخصص",
    "catering.service.corporate": "تموين شركات",
    "catering.service.corporateDesc": "حلول تموين مخصصة للشركات والفعاليات المؤسسية",
    "catering.service.carcass": "ذبائح كاملة",
    "catering.service.carcassDesc": "خدمة ذبائح شاملة مع التقطيع والتجهيز حسب رغبتكم",
    "catering.stats": "مناسبة ناجحة سنويًا",
    "catering.feature.customMenus": "قوائم مخصصة",
    "catering.feature.fullSetup": "تجهيز كامل",
    "catering.feature.proStaff": "طاقم خدمة محترف",
    "catering.feature.onTimeDelivery": "توصيل في الوقت المحدد",
    "catering.feature.luxuryBuffets": "بوفيهات فاخرة",
    "catering.feature.vipService": "خدمة VIP",
    "catering.feature.fullCoordination": "تنسيق كامل",
    "catering.feature.diverseMenus": "قوائم متنوعة",
    "catering.feature.familyEvents": "مناسبات عائلية",
    "catering.feature.gatherings": "عزائم",
    "catering.feature.privateParties": "حفلات خاصة",
    "catering.feature.wholeCarcass": "ذبائح كاملة",
    "catering.feature.liveGrill": "شوي مباشر",
    "catering.feature.specializedStaff": "طاقم متخصص",
    "catering.feature.fullEquipment": "معدات كاملة",
    "catering.feature.premiumMeats": "لحوم فاخرة",
    
    // Contact Section & Page
    "contact.tagline": "تواصل معنا",
    "contact.title": "تواصل مع ملحمة السرايا",
    "contact.description": "نحن دائمًا في خدمتك — تواصل معنا للطلبات، الاستفسارات، أو خدمات التموين.",
    "contact.sendMessage": "أرسل لنا رسالة",
    "contact.name": "الاسم",
    "contact.namePlaceholder": "اسمك الكريم",
    "contact.phone": "الهاتف",
    "contact.phonePlaceholder": "رقم الهاتف",
    "contact.email": "البريد الإلكتروني",
    "contact.emailPlaceholder": "بريدك الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.subjectPlaceholder": "موضوع الرسالة",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "اكتب رسالتك هنا...",
    "contact.whatsappTitle": "تواصل عبر واتساب",
    "contact.whatsappDescription": "للطلبات السريعة والاستفسارات الفورية",
    "contact.location": "الموقع",
    "contact.locationValue": "أبوظبي، الإمارات العربية المتحدة",
    "contact.hours": "ساعات العمل",
    "contact.hoursValue": "8 صباحًا - 11 مساءً",
    "contact.openInMaps": "افتح في خرائط Google",
    "contact.messageSent": "تم إرسال رسالتك بنجاح",
    "contact.messageResponse": "سنتواصل معك في أقرب وقت ممكن",
    "contact.alwaysAtService": "نحن دائمًا في خدمتك — تواصل معنا للطلبات أو الاستفسارات",
    
    // Cart
    "cart.title": "سلة التسوق",
    "cart.items": "منتجات",
    "cart.empty": "سلة التسوق فارغة",
    "cart.emptyTitle": "سلة التسوق فارغة",
    "cart.emptyDescription": "لم تقم بإضافة أي منتجات إلى سلة التسوق بعد. تصفح منتجاتنا وأضف ما تريد!",
    "cart.continueShopping": "متابعة التسوق",
    "cart.startShopping": "ابدأ التسوق",
    "cart.subtotal": "المجموع الفرعي",
    "cart.delivery": "التوصيل",
    "cart.freeDelivery": "مجاني",
    "cart.freeDeliveryNote": "توصيل مجاني للطلبات فوق 250 درهم",
    "cart.total": "الإجمالي",
    "cart.currency": "د.إ",
    "cart.checkout": "إتمام الطلب",
    "cart.proceedToCheckout": "متابعة الدفع",
    "cart.orderSummary": "ملخص الطلب",
    "cart.minimumOrder": "الحد الأدنى للطلب",
    "cart.minimumOrderTitle": "الحد الأدنى للطلب غير مستوفى",
    "cart.minimumOrderDesc": "الحد الأدنى للطلب هو {amount} درهم",
    "cart.minimumNotMet": "الحد الأدنى للطلب غير مستوفى",
    "cart.clearCart": "تفريغ السلة",
    "cart.secureCheckout": "دفع آمن",
    "cart.freshGuarantee": "ضمان الطازجة",
    "cart.inCart": "في السلة",
    "cart.totalWeight": "الوزن الإجمالي",
    "cart.notes": "ملاحظات خاصة",
    "cart.orderWhatsApp": "اطلب عبر واتساب",
    
    // Products
    "products.selectWeight": "اختر الوزن",
    "products.pricePerKg": "السعر/كيلو",
    "products.total": "الإجمالي",
    "products.addToCart": "أضف للسلة",
    "products.added": "تمت الإضافة",
    "products.notesPlaceholder": "اكتب ملاحظاتك (تقطيع – تتبيل – سمك الشرائح...)",
    "products.notesHint": "مثال: تقطيع ناعم، بدون دهون، تتبيلة خاصة",
    "products.quantity": "الكمية",
    "products.boxNotesPlaceholder": "ملاحظات خاصة للبوكس (مثال: بدون بصل، إضافة صوص...)",
    
    // Checkout
    "checkout.title": "إتمام الطلب",
    "checkout.subtitle": "أكمل بياناتك لإتمام طلبك",
    "checkout.backToCart": "العودة للسلة",
    "checkout.customerInfo": "معلومات العميل",
    "checkout.name": "الاسم الكامل",
    "checkout.namePlaceholder": "أدخل اسمك الكامل",
    "checkout.phone": "رقم الهاتف",
    "checkout.phonePlaceholder": "05xxxxxxxx",
    "checkout.email": "البريد الإلكتروني",
    "checkout.emailPlaceholder": "example@email.com",
    "checkout.deliveryAddress": "عنوان التوصيل",
    "checkout.address": "العنوان التفصيلي",
    "checkout.addressPlaceholder": "المنطقة، الشارع، رقم المبنى، الشقة...",
    "checkout.city": "المدينة",
    "checkout.cityNote": "التوصيل متاح حاليًا في أبوظبي فقط",
    "checkout.notes": "ملاحظات إضافية",
    "checkout.notesPlaceholder": "أي تعليمات خاصة للتوصيل...",
    "checkout.paymentMethod": "طريقة الدفع",
    "checkout.onlinePayment": "الدفع الإلكتروني",
    "checkout.onlinePaymentDesc": "فيزا، ماستركارد، أبل باي",
    "checkout.cashOnDelivery": "الدفع عند الاستلام",
    "checkout.codDesc": "ادفع نقدًا عند استلام طلبك",
    "checkout.placeOrder": "تأكيد الطلب",
    "checkout.payNow": "ادفع الآن",
    "checkout.processing": "جاري المعالجة...",
    "checkout.orOrderVia": "أو اطلب عبر",
    "checkout.orderWhatsApp": "اطلب عبر واتساب",
    "checkout.whatsappOrder": "مرحبًا، أريد تأكيد طلبي:",
    "checkout.errorTitle": "خطأ",
    "checkout.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "checkout.successTitle": "تم الطلب بنجاح!",
    "checkout.codSuccess": "شكرًا لك! سيتم التواصل معك قريبًا لتأكيد الطلب",
    "checkout.processingPayment": "جاري معالجة الدفع",
    "checkout.redirecting": "سيتم تحويلك لصفحة الدفع...",
    "checkout.emptyCart": "سلة التسوق فارغة",
    "checkout.emptyCartDesc": "أضف منتجات إلى سلتك للمتابعة",
    "checkout.comingSoon": "الطلب الإلكتروني قريباً",
    "checkout.comingSoonDesc": "نعمل على تفعيل الدفع الإلكتروني والتوصيل. حالياً، اطلب عبر واتساب!",
    "checkout.comingSoonButton": "قريباً...",
    "checkout.iikoStatus": "جاري الربط مع نظام iiko POS",
    "checkout.iikoStatusReady": "✓ نظام iiko POS جاهز - Fail-Safe مفعّل",
    "checkout.codActive": "الدفع عند الاستلام متاح",
    "checkout.codActiveDesc": "اطلب الآن وادفع نقداً عند استلام طلبك!",
    "checkout.orderError": "حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.",
    "checkout.invalidPhone": "يرجى إدخال رقم هاتف صحيح (مثال: 0501234567)",
    
    // Order Success
    "orderSuccess.title": "تم استلام طلبك!",
    "orderSuccess.description": "شكرًا لك! تم استلام طلبك وسيتم التواصل معك قريبًا لتأكيد التفاصيل والتوصيل.",
    "orderSuccess.whatNext": "ماذا بعد؟",
    "orderSuccess.whatNextDesc": "سيتواصل معك فريقنا خلال ساعة لتأكيد الطلب وموعد التوصيل.",
    "orderSuccess.backHome": "العودة للرئيسية",
    "orderSuccess.continueShopping": "متابعة التسوق",
    "orderSuccess.needHelp": "تحتاج مساعدة؟",
    "orderSuccess.contactUs": "تواصل معنا عبر واتساب",
    
    // Footer
    "footer.description": "نقدم أجود أنواع اللحوم الطازجة والحلال، مع التزامنا بأعلى معايير الجودة والنظافة. خبرة تمتد لأكثر من 14 عامًا في خدمة عملائنا.",
    "footer.quickLinks": "روابط سريعة",
    "footer.shopCategories": "أقسام الملحمة",
    "footer.contactUs": "تواصل معنا",
    "footer.followUs": "تابعنا",
    "footer.rights": "جميع الحقوق محفوظة",
    
    // Recipes
    "recipes.tagline": "الوصفات",
    "recipes.title": "وصفات السرايا",
    "recipes.description": "وصفات احترافية من طهاة ملحمة السرايا — تعلّم أفضل طرق تحضير المشاوي باستخدام لحومنا الطازجة",
    "recipes.readRecipe": "اقرأ الوصفة",
    "recipes.allRecipes": "جميع الوصفات",
    "recipes.minutes": "دقيقة",
    "recipes.people": "أشخاص",
    "recipes.difficulty.easy": "سهل",
    "recipes.difficulty.medium": "متوسط",
    "recipes.difficulty.hard": "صعب",
    "recipes.introduction": "مقدمة",
    "recipes.recommendedCut": "القطعة الموصى بها",
    "recipes.ingredients": "المكونات",
    "recipes.chefTips": "نصائح الطهاة",
    "recipes.preparationMethod": "طريقة التحضير",
    "recipes.readyToPrepare": "جاهز لتحضير هذه الوصفة؟",
    "recipes.orderIngredientsMessage": "اطلب المكونات الطازجة من ملحمة السرايا واستمتع بأفضل نتيجة",
    "recipes.notFound": "الوصفة غير موجودة",
    "recipes.notFoundDesc": "عذرًا، لم نتمكن من العثور على هذه الوصفة",
    "recipes.discoverRecipes": "اكتشف وصفاتنا المميزة",
    "recipes.discoverDescription": "وصفات احترافية من طهاة ملحمة السرايا لتحضير أشهى الأطباق",
    
    // Recipe Items
    "recipe.lambRibs.title": "ريش غنم مشوية على الفحم",
    "recipe.lambRibs.desc": "وصفة ريش الغنم المشوية على الفحم بتتبيلة عربية أصيلة للعزائم",
    "recipe.shishTaouk.title": "شيش طاووق شامي",
    "recipe.shishTaouk.desc": "شيش طاووق على الطريقة الشامية بتتبيلة اللبن والتوابل العربية",
    "recipe.kebab.title": "كباب لحم على الطريقة الشامية",
    "recipe.kebab.desc": "كباب حلبي أصيل بالبهارات العربية والبصل - وصفة المطاعم الفاخرة",
    
    // Menu Section & Page
    "menu.tagline": "قائمة الطعام",
    "menu.title": "قائمة مشاوي السرايا",
    "menu.description": "مشاوي طازجة تُحضّر يوميًا باستخدام لحومنا المختارة، بتتبيل شامي أصيل وطعم لا يُنسى.",
    "menu.popular": "الأكثر طلبًا",
    "menu.viewFullMenu": "عرض القائمة الكاملة",
    "menu.currency": "د.إ",
    "menu.readyToOrder": "جاهز للطلب؟",
    "menu.orderNowMessage": "اطلب الآن عبر واتساب واستمتع بألذ المشاوي الشامية الأصيلة",
    "menu.grills": "المشاوي",
    "menu.appetizers": "المقبلات",
    "menu.steaks": "الستيك",
    "menu.mainDishes": "الأطباق الرئيسية",
    "menu.salads": "السلطات",
    "menu.beverages": "المشروبات",
    
    // Menu Items
    "menu.mixedGrill.name": "مشكل مشاوي السرايا",
    "menu.mixedGrill.desc": "تشكيلة فاخرة من الكباب والشقف والريش مع الخضار المشوية",
    "menu.lambRibs.name": "ريش غنم مشوية",
    "menu.lambRibs.desc": "ريش غنم طرية متبلة بخلطة السرايا الخاصة",
    "menu.beefKebab.name": "كباب لحم بقري",
    "menu.beefKebab.desc": "كباب لحم بقري طازج مع البهارات الشامية الأصيلة",
    "menu.shaqf.name": "شقف لحم",
    "menu.shaqf.desc": "قطع لحم مشوية على الفحم مع الطماطم والفلفل",
    "menu.herbChicken.name": "دجاج مشوي بالأعشاب",
    "menu.herbChicken.desc": "نصف دجاجة مشوية مع أعشاب البحر المتوسط",
    "menu.filletSteak.name": "ستيك فيليه",
    "menu.filletSteak.desc": "ستيك فيليه مشوي بدرجة الاستواء المطلوبة",
    
    // Trust Badges
    "trust.halal": "100% حلال",
    "trust.halalDesc": "مذبوحة وفق الشريعة",
    "trust.quality": "جودة ممتازة",
    "trust.qualityDesc": "أجود قطوعات اللحوم",
    "trust.delivery": "توصيل سريع",
    "trust.deliveryDesc": "لباب منزلك",
    "trust.fresh": "طازج يوميًا",
    "trust.freshDesc": "لحوم طازجة كل يوم",
    "trust.experience": "+6 سنوات خبرة",
    "trust.experienceDesc": "خبرة تضمن الجودة",
    "trust.customers": "+10,000 عميل",
    "trust.customersDesc": "عملاء سعداء",
    
    // Delivery Section
    "delivery.service": "خدمة التوصيل",
    "delivery.title": "لحوم طازجة لباب منزلك",
    "delivery.description": "نوصل لك أجود اللحوم الطازجة والحلال بأسرع وقت ممكن. اطلب الآن واستمتع بجودة لا مثيل لها.",
    "delivery.fast": "توصيل سريع",
    "delivery.fastDesc": "خلال ساعات قليلة",
    "delivery.coverage": "تغطية واسعة",
    "delivery.coverageDesc": "أبوظبي والعين والمناطق المجاورة",
    
    // Why Choose Us Section
    "whyChoose.title": "لماذا ملحمة السرايا؟",
    "whyChoose.subtitle": "جودة لا تُضاهى وثقة لا تُنسى",
    "whyChoose.fresh.title": "لحوم طازجة يومياً",
    "whyChoose.fresh.desc": "نختار أجود اللحوم الطازجة يومياً من مصادر موثوقة",
    "whyChoose.cutting.title": "تقطيع احترافي حسب الطلب",
    "whyChoose.cutting.desc": "فريق متخصص يقطّع اللحوم حسب رغبتك بدقة عالية",
    "whyChoose.hygiene.title": "أعلى معايير النظافة",
    "whyChoose.hygiene.desc": "نلتزم بأعلى معايير النظافة والجودة في كل خطوة",
    "whyChoose.trust.title": "ثقة منذ 2019",
    "whyChoose.trust.desc": "أكثر من 6 سنوات من الخبرة وخدمة آلاف العملاء",
    
    // Best Sellers Section
    "bestSellers.tagline": "الأكثر طلباً",
    "bestSellers.title": "اختياراتنا المميزة 🔥",
    "bestSellers.viewAll": "عرض جميع المنتجات",
    "bestSellers.orderNow": "اطلب الآن",
    "bestSellers.perKg": "للكيلو",
    
    // How To Order Section
    "howToOrder.title": "اطلب في 4 خطوات بسيطة 👌",
    "howToOrder.subtitle": "بدون تعقيد – بدون انتظار – جودة مضمونة 🥩",
    "howToOrder.step1.title": "اختر اللحم",
    "howToOrder.step1.desc": "تصفح اختياراتنا من اللحوم الطازجة واختر اللي يناسبك",
    "howToOrder.step2.title": "حدّد التقطيع والكمية",
    "howToOrder.step2.desc": "اختار طريقة التقطيع والكمية حسب احتياجك",
    "howToOrder.step3.title": "اطلب أونلاين أو واتساب",
    "howToOrder.step3.desc": "اطلب بسهولة من الموقع أو مباشرة عبر واتساب",
    "howToOrder.step4.title": "استلم لحمك طازج",
    "howToOrder.step4.desc": "نجهز طلبك بعناية ويوصل لحد باب بيتك",
    "howToOrder.trustMessage": "طلبات يومية من آلاف العملاء السعداء",
    
    // Trust Stats Section
    "trustStats.title": "ثقة الآلاف",
    "trustStats.subtitle": "أرقام تتحدث عن جودتنا",
    "trustStats.customers": "عميل سعيد",
    "trustStats.rating": "تقييم العملاء",
    "trustStats.years": "سنوات خبرة",
    "trustStats.halal": "لحوم حلال",
    
    // Final CTA Section
    "finalCTA.title": "جاهز تطلب لحم طازج النهارده؟",
    "finalCTA.subtitle": "اختار الصح وخليك مطمّن",
    "finalCTA.whatsapp": "اطلب عبر واتساب",
    "finalCTA.order": "اطلب الآن",
    "finalCTA.trust": "🥩 لحوم طازجة 100% حلال • توصيل سريع • دفع آمن",
    
    // Delivery & Payment Section
    "deliveryPayment.title": "توصيل ودفع",
    "deliveryPayment.subtitle": "توصيل سريع – دفع آمن – تجربة مريحة من أول طلب",
    "deliveryPayment.fast.title": "توصيل سريع",
    "deliveryPayment.fast.desc": "توصيل لجميع مناطق الإمارات",
    "deliveryPayment.sameDay.title": "تحضير في نفس اليوم",
    "deliveryPayment.sameDay.desc": "نجهز طلبك طازجاً عند الطلب",
    "deliveryPayment.secure.title": "دفع آمن",
    "deliveryPayment.secure.desc": "معاملات مشفرة وآمنة 100%",
    "deliveryPayment.cod.title": "الدفع عند الاستلام",
    "deliveryPayment.cod.desc": "متاح لراحتك",
    "deliveryPayment.methods": "طرق الدفع المتاحة",
    "deliveryPayment.poweredBy": "بوابة دفع Network International",
    
    // Saraya Boxes Section
    "sarayaBoxes.tagline": "عروض مميزة",
    "sarayaBoxes.title": "بوكسات خاصة",
    "sarayaBoxes.subtitle": "بوكسات متكاملة جاهزة للشوي والحفلات - كل ما تحتاجه في بوكس واحد",
    "sarayaBoxes.trending": "ترند",
    "sarayaBoxes.bestSeller": "الأكثر طلباً",
    "sarayaBoxes.orderWhatsapp": "اطلب الآن عبر واتساب",
    "sarayaBoxes.currency": "د.إ",
    "sarayaBoxes.comingSoon": "المزيد من البوكسات قريباً...",
    "sarayaBoxes.viewAll": "عرض جميع البوكسات",
    
    // WhatsApp CTA
    "whatsapp.orderNow": "اطلب الآن!",
    "whatsapp.getFreshMeat": "احصل على لحم طازج اليوم",
    "whatsapp.contactVia": "تواصل عبر واتساب",
    "whatsapp.fastDelivery": "توصيل سريع",
    "whatsapp.freshDaily": "طازج يوميًا",
    "whatsapp.halal100": "100% حلال",
    "whatsapp.defaultMessage": "مرحبًا، أريد طلب لحوم طازجة",
    
    // Order Tracking
    "tracking.title": "تتبع طلبك",
    "tracking.subtitle": "تابع حالة طلبك وموقع السائق مباشرة",
    "tracking.searchPlaceholder": "أدخل رقم الطلب",
    "tracking.search": "بحث",
    "tracking.orderNotFound": "الطلب غير موجود",
    "tracking.orderNotFoundDesc": "لم نتمكن من العثور على طلب بهذا الرقم",
    "tracking.tryAgain": "حاول مرة أخرى",
    "tracking.startDemo": "تشغيل العرض التجريبي",
    "tracking.demoMode": "عرض تجريبي",
    "tracking.comingSoon": "نظام التتبع قيد التطوير",
    "tracking.comingSoonDesc": "نعمل على تفعيل نظام التتبع المباشر",
    "tracking.liveTracking": "تتبع السائق مباشرة",
    "tracking.deliveryLocation": "عنوان التوصيل",
    "tracking.estimatedArrival": "الوقت المتوقع للوصول",
    "tracking.needHelp": "تحتاج مساعدة؟",
    "tracking.callUs": "اتصل بنا",
    "tracking.backToHome": "العودة للرئيسية",
    
    // Driver Panel
    "driver.title": "لوحة السائق",
    "driver.subtitle": "إدارة التوصيلات وتتبع الموقع",
    "driver.currentOrder": "الطلب الحالي",
    "driver.orderNumber": "رقم الطلب",
    "driver.deliveryAddress": "عنوان التوصيل",
    "driver.locationTracking": "تتبع الموقع",
    "driver.sharingLocation": "يتم مشاركة موقعك",
    "driver.trackingOff": "التتبع متوقف",
    "driver.start": "بدء",
    "driver.stop": "إيقاف",
    "driver.deliveryActions": "إجراءات التوصيل",
    "driver.startDelivery": "بدء التوصيل",
    "driver.markDelivered": "تم التوصيل",
    "driver.deliveredSuccess": "تم التوصيل بنجاح!",
    "driver.callCustomer": "اتصل بالعميل",
    "driver.openInMaps": "فتح في الخرائط",
    "driver.noOrders": "لا توجد طلبات",
    "driver.noOrdersDesc": "لم يتم تعيين أي طلبات لك حالياً",
    
    // Admin Dashboard
    "admin.title": "لوحة إدارة التوصيل",
    "admin.subtitle": "إدارة الطلبات والسائقين",
    "admin.pendingOrders": "طلبات قيد الانتظار",
    "admin.activeDeliveries": "توصيلات نشطة",
    "admin.availableDrivers": "سائقين متاحين",
    "admin.deliveredToday": "تم التوصيل اليوم",
    "admin.allOrders": "جميع الطلبات",
    "admin.refresh": "تحديث",
    "admin.assignDriver": "تعيين سائق",
    "admin.noDriversAvailable": "لا يوجد سائقين متاحين",
    "admin.driverManagement": "إدارة السائقين",
    "admin.activeDrivers": "السائقين النشطين",
    "admin.panel": "لوحة الإدارة",
    "admin.products": "المنتجات",
    "admin.productsManagement": "إدارة المنتجات",
    "admin.addProduct": "إضافة منتج",
    "admin.editProduct": "تعديل المنتج",
    "admin.deleteProduct": "حذف المنتج",
    "admin.orders": "الطلبات",
    "admin.ordersManagement": "إدارة الطلبات",
    "admin.orderNumber": "رقم الطلب",
    "admin.customer": "العميل",
    "admin.status": "الحالة",
    "admin.total": "الإجمالي",
    "admin.date": "التاريخ",
    "admin.actions": "إجراءات",
    "admin.settings": "الإعدادات",
    "admin.deliverySettings": "إعدادات التوصيل",
    "admin.deliveryZones": "مناطق التوصيل",
    "admin.addZone": "إضافة منطقة",
    "admin.deleteZone": "حذف المنطقة",
    "admin.deliveryFee": "رسوم التوصيل",
    "admin.freeDeliveryThreshold": "حد التوصيل المجاني",
    "admin.estimatedTime": "وقت التوصيل المتوقع",
    "admin.save": "حفظ",
    "admin.cancel": "إلغاء",
    "admin.confirm": "تأكيد",
    "admin.error": "خطأ",
    "admin.success": "نجاح",
    "admin.loading": "جاري التحميل...",
    "admin.noData": "لا توجد بيانات",
    "admin.search": "بحث",
    "admin.filter": "تصفية",
    "admin.export": "تصدير",
    "admin.import": "استيراد",
    "admin.image": "صورة",
    "admin.name": "الاسم",
    "admin.price": "السعر",
    "admin.category": "القسم",
    "admin.active": "نشط",
    "admin.inactive": "غير نشط",
    "admin.view": "عرض",
    "admin.edit": "تعديل",
    "admin.delete": "حذف",
    "admin.chooseImage": "اختر صورة",
    "admin.uploading": "جاري الرفع...",
    "admin.uploadSuccess": "تم رفع الصورة بنجاح",
    "admin.uploadError": "خطأ في رفع الصورة",
    
    // Sticky CTA
    "stickyCTA.title": "جاهز للطلب؟",
    "stickyCTA.subtitle": "لحوم طازجة لباب بيتك",
    "stickyCTA.button": "اطلب الآن",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.butchery": "Butchery",
    "nav.restaurant": "Restaurant",
    "nav.catering": "Catering",
    "nav.menu": "Menu",
    "nav.recipes": "Recipes",
    "nav.blog": "Blog",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.offers": "Offers",
    "nav.viewAll": "View All",
    
    // Shop Categories
    "shop.beef": "Beef",
    "shop.lamb": "Lamb",
    "shop.chicken": "Chicken",
    "shop.readyToGrill": "Ready to Grill",
    "shop.specialCuts": "Special Cuts",
    "shop.boxes": "Special Boxes",
    "shop.sections": "Categories",
    "shop.showing": "Showing",
    "shop.products": "products",
    "shop.noProducts": "No products in this category",
    "shop.discoverCollection": "Discover our selected range of fresh halal meats",
    
    // Catering Services
    "catering.corporate": "Corporate Catering",
    "catering.wedding": "Wedding Catering",
    "catering.events": "Event Catering",
    "catering.bbq": "BBQ Catering",
    "catering.aboutService": "About",
    "catering.serviceFeatures": "Service Features",
    "catering.serviceIntro": "At Al Saraya Butchery, we provide catering services with the highest quality and professionalism. We ensure the finest fresh meats with specialized staff to guarantee your event's success.",
    "catering.serviceIntroEn": "At Al Saraya Butchery, we provide catering services with the highest quality and professionalism. We ensure the finest fresh meats with specialized staff to guarantee your event's success.",
    "catering.getQuote": "Get a Quote",
    "catering.ourWorks": "Our Work",
    "catering.haveEvent": "Have an upcoming event?",
    "catering.eventDescription": "Contact us now for a custom quote for your event. Our team is ready to help you create an unforgettable occasion.",
    "catering.contactPage": "Contact Page",
    "catering.serviceNotFound": "Service Not Found",
    "catering.serviceNotFoundDesc": "Sorry, we couldn't find this service",
    "catering.mainDescription": "We offer comprehensive catering services for private events using the finest meats",
    "catering.learnMore": "Learn More",
    
    // Restaurant Categories
    "restaurant.bbq": "BBQ",
    "restaurant.pottery": "Pottery Dishes",
    "restaurant.sandwiches": "Sandwiches",
    "restaurant.fattat": "Fattat & Foul",
    "restaurant.shamyat": "Shamyat",
    "restaurant.manakeesh": "Manakeesh",
    "restaurant.appetizers": "Appetizers",
    "restaurant.salads": "Salads",
    "restaurant.drinks": "Drinks",
    "restaurant.menuSections": "Menu Sections",
    "restaurant.showAll": "View All",
    "restaurant.allItems": "All Items",
    "restaurant.items": "items",
    "restaurant.readyToOrder": "Ready to order? Contact us now!",
    "restaurant.fastDelivery": "Fast delivery to your door in Abu Dhabi",
    "restaurant.deliveryAvailable": "Delivery available in Abu Dhabi",
    "restaurant.tagline": "At Al Saraya, cooking from the heart, flavor from memory",
    "restaurant.taglineEn": "At Al Saraya, cooking from the heart, flavor from memory",
    
    // Buttons & CTAs
    "cta.callUs": "Call Us",
    "cta.orderNow": "Order Now",
    "cta.whatsapp": "WhatsApp",
    "cta.learnMore": "Learn More",
    "cta.viewMenu": "View Menu",
    "cta.viewAll": "View All",
    "cta.sendMessage": "Send Message",
    "cta.startChat": "Start Chat",
    "cta.orderWhatsapp": "Order via WhatsApp",
    "cta.browseProducts": "Browse All Products",
    "cta.orderNowWhatsapp": "Order Now via WhatsApp",
    "cta.getFreshMeat": "Get Fresh Meat Today",
    "cta.browseMenu": "Browse Menu",
    "cta.learnMoreAbout": "Learn More About Us",
    "cta.exploreServices": "Explore Our Services",
    "cta.getQuote": "Get a Quote",
    "cta.shopNow": "Shop Now",
    "cta.contactUs": "Contact Us",
    "cta.browseProductsPage": "Browse Products",
    "cta.buyNow": "Buy Now",
    "cta.orderViaWhatsapp": "Order via WhatsApp",
    "cta.shopIngredients": "Shop Ingredients",
    "cta.allRecipes": "All Recipes",
    "cta.orderWhatsappNow": "Order via WhatsApp",
    
    // Header
    "header.title": "Al Saraya Butchery",
    "header.subtitle": "ملحمة السرايا",
    "header.searchPlaceholder": "Search products...",
    
    // Hero Section
    "hero.badge": "Unmatched Quality Since 2019",
    "hero.title": "Al Saraya Butchery",
    "hero.subtitle": "Where Meat Quality Begins and Trust Begins",
    "hero.description": "At Al Saraya Butchery, we offer carefully selected fresh meats, expertly cut and prepared to suit all tastes — from family barbecues to grand feasts and events.",
    "hero.stats.years": "Years of Experience",
    "hero.stats.customers": "Happy Customers",
    "hero.stats.halal": "Halal Meats",
    
    // About Section & Page
    "about.tagline": "About Us",
    "about.title": "The Al Saraya Story",
    "about.description1": "Al Saraya Butchery was established to provide fresh, high-quality meats that earn our customers' trust day after day. We are proud to be the first choice for families and restaurants seeking quality.",
    "about.description2": "We adhere to the highest standards of halal slaughter, hygiene, and careful selection, ensuring you a comfortable shopping experience and unforgettable taste.",
    "about.experience": "Years of Excellence",
    "about.feature.halal": "Halal Slaughter",
    "about.feature.halalDesc": "All our meats are slaughtered according to Islamic law",
    "about.feature.fresh": "Fresh Daily",
    "about.feature.freshDesc": "Fresh meats delivered directly from the farm",
    "about.feature.quality": "Guaranteed Quality",
    "about.feature.qualityDesc": "Highest standards of quality and hygiene in the industry",
    "about.feature.service": "Excellent Service",
    "about.feature.serviceDesc": "Professional team ensuring your complete satisfaction",
    "about.storyTagline": "Our Story",
    "about.storyTitle": "A Journey of Excellence in Meat",
    "about.storyP1": "Al Saraya Butchery was founded in 2010 with a clear goal: to provide the finest fresh halal meats to our customers in the UAE.",
    "about.storyP2": "We started as a small family-run butchery, and today we are proud to be the preferred destination for families and restaurants seeking quality and trust.",
    "about.storyP3": "We adhere to the highest standards of halal slaughter, hygiene, and careful selection, ensuring you a comfortable shopping experience and unforgettable taste every time.",
    "about.storyP4": "Our specialized team ensures the selection of the best local and imported meats, expertly cut and ready to meet your needs.",
    "about.valuesTagline": "Our Values",
    "about.valuesTitle": "What Sets Us Apart",
    "about.valuesDescription": "We commit to a set of values that guarantee you the best experience with every interaction",
    "about.value.halalSlaughter": "Halal Slaughter",
    "about.value.halalSlaughterDesc": "All our meats are slaughtered according to Islamic law by specialists",
    "about.value.freshDaily": "Fresh Daily",
    "about.value.freshDailyDesc": "Fresh meats delivered directly from the farm every day",
    "about.value.qualityGuaranteed": "Quality Guaranteed",
    "about.value.qualityGuaranteedDesc": "Highest standards of quality and hygiene at every stage",
    "about.value.excellentService": "Excellent Service",
    "about.value.excellentServiceDesc": "Professional team ensuring your complete satisfaction in every interaction",
    "about.value.longExperience": "Extensive Experience",
    "about.value.longExperienceDesc": "Over 14 years of experience serving our customers",
    "about.value.fastDelivery": "Fast Delivery",
    "about.value.fastDeliveryDesc": "Fast delivery service ensuring fresh meat arrives to you",
    "about.teamTagline": "Our Team",
    "about.teamTitle": "Al Saraya Butchery Team",
    "about.teamDescription": "We are proud of our professional team that ensures the best quality and service",
    "about.butcheryTeam": "Butchery Team",
    "about.butcheryTeamDesc": "Professional butchers and chefs with extensive experience in providing the finest meats",
    "about.deliveryTeam": "Delivery Team",
    "about.deliveryTeamDesc": "Specialized delivery team ensuring your order arrives fresh and on time",
    "about.successTeam": "Success Team",
    "about.generalManager": "General Manager & Supervisor",
    "about.managerDesc": "The advertising face of the butchery and supervisor since its establishment",
    "about.socialMediaManager": "Social Media & Web Manager",
    "about.socialMediaManagerDesc": "Digital marketing and website development manager",
    "about.joinFamily": "Join the Al Saraya Family",
    "about.alwaysAtService": "We are always at your service. Contact us for orders or inquiries",
    "about.stats.years": "Years of Experience",
    "about.stats.customers": "Happy Customers",
    "about.stats.events": "Events Annually",
    "about.stats.halal": "Halal Meats",
    
    // Products Section
    "products.tagline": "Our Products",
    "products.title": "Featured Products",
    "products.description": "Discover our selected range of fresh halal meats, prepared daily with the highest quality standards.",
    "products.new": "New",
    "products.sale": "Sale",
    "products.currency": "AED",
    
    // Product Names
    "product.ribEye": "Rib Eye Steak",
    "product.ribEyeDesc": "Premium rib eye cut with perfect fat distribution",
    "product.beefKebab": "Beef Kebab",
    "product.beefKebabDesc": "Fresh beef kebab with Levantine spices",
    "product.lambRibs": "Lamb Ribs",
    "product.lambRibsDesc": "Tender lamb ribs marinated with special blend",
    "product.chickenShawarma": "Ready Chicken Shawarma",
    "product.chickenShawarmaDesc": "Marinated chicken shawarma ready for grilling",
    "product.groundBeef": "Ground Beef",
    "product.groundBeefDesc": "Fresh ground beef for kebab and kofta",
    "product.familyBBQ": "Family BBQ Box",
    "product.familyBBQDesc": "Assorted meat selection for the family",
    
    // Testimonials Section
    "testimonials.tagline": "Customer Reviews",
    "testimonials.title": "What Our Customers Say",
    "testimonials.description": "Our customers' trust is our true capital, and their experience with us is proof of the quality we deliver.",
    
    // Testimonial Content
    "testimonial.1.name": "Ahmed Mohammed",
    "testimonial.1.role": "Regular Customer",
    "testimonial.1.content": "Best butchery in Dubai! The meat is always fresh and the cut quality is excellent. Fast delivery and very professional service.",
    "testimonial.2.name": "Sara Al Ali",
    "testimonial.2.role": "Restaurant Owner",
    "testimonial.2.content": "We've been working with Al Saraya Butchery for 3 years for our restaurant. Consistent quality and competitive prices. A trusted partner for our business.",
    "testimonial.3.name": "Khaled Al Hammadi",
    "testimonial.3.role": "BBQ Enthusiast",
    "testimonial.3.content": "Amazing experience! Ordered the BBQ box for a family party and everyone was happy with the meat quality and authentic Levantine marinade.",
    "testimonial.4.name": "Fatima Al Shamsi",
    "testimonial.4.role": "Homemaker",
    "testimonial.4.content": "The catering service for our Ramadan gathering was perfect! Thanks to the Al Saraya team for their professionalism and quality.",
    
    // Catering Section
    "catering.tagline": "Catering Services",
    "catering.title": "Catering & Event Services",
    "catering.description": "Al Saraya Butchery offers comprehensive catering services for private events, gatherings, parties, and corporate functions, using the finest meats and professional preparation.",
    "catering.service.wedding": "Wedding & Event Catering",
    "catering.service.weddingDesc": "Complete catering services for weddings and special occasions with the finest meats",
    "catering.service.bbq": "BBQ Party Catering",
    "catering.service.bbqDesc": "Professional BBQ service at your location with full setup and specialized staff",
    "catering.service.corporate": "Corporate Catering",
    "catering.service.corporateDesc": "Customized catering solutions for companies and corporate events",
    "catering.service.carcass": "Whole Carcass",
    "catering.service.carcassDesc": "Complete carcass service with cutting and preparation to your preference",
    "catering.stats": "Successful Events Annually",
    "catering.feature.customMenus": "Custom Menus",
    "catering.feature.fullSetup": "Full Setup",
    "catering.feature.proStaff": "Professional Staff",
    "catering.feature.onTimeDelivery": "On-Time Delivery",
    "catering.feature.luxuryBuffets": "Luxury Buffets",
    "catering.feature.vipService": "VIP Service",
    "catering.feature.fullCoordination": "Full Coordination",
    "catering.feature.diverseMenus": "Diverse Menus",
    "catering.feature.familyEvents": "Family Events",
    "catering.feature.gatherings": "Gatherings",
    "catering.feature.privateParties": "Private Parties",
    "catering.feature.wholeCarcass": "Whole Carcass",
    "catering.feature.liveGrill": "Live Grill",
    "catering.feature.specializedStaff": "Specialized Staff",
    "catering.feature.fullEquipment": "Full Equipment",
    "catering.feature.premiumMeats": "Premium Meats",
    
    // Contact Section & Page
    "contact.tagline": "Get in Touch",
    "contact.title": "Contact Al Saraya Butchery",
    "contact.description": "We are always at your service — contact us for orders, inquiries, or catering services.",
    "contact.sendMessage": "Send us a message",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your name",
    "contact.phone": "Phone",
    "contact.phonePlaceholder": "Phone number",
    "contact.email": "Email",
    "contact.emailPlaceholder": "Your email",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "Message subject",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Write your message here...",
    "contact.whatsappTitle": "Contact via WhatsApp",
    "contact.whatsappDescription": "For quick orders and instant inquiries",
    "contact.location": "Location",
    "contact.locationValue": "Abu Dhabi, UAE",
    "contact.hours": "Working Hours",
    "contact.hoursValue": "8 AM - 11 PM",
    "contact.openInMaps": "Open in Google Maps",
    "contact.messageSent": "Your message was sent successfully",
    "contact.messageResponse": "We will contact you as soon as possible",
    "contact.alwaysAtService": "We are always at your service — contact us for orders or inquiries",
    
    // Cart
    "cart.title": "Shopping Cart",
    "cart.items": "items",
    "cart.empty": "Your cart is empty",
    "cart.emptyTitle": "Your Cart is Empty",
    "cart.emptyDescription": "You haven't added any products to your cart yet. Browse our products and add what you like!",
    "cart.continueShopping": "Continue Shopping",
    "cart.startShopping": "Start Shopping",
    "cart.subtotal": "Subtotal",
    "cart.delivery": "Delivery",
    "cart.freeDelivery": "Free",
    "cart.freeDeliveryNote": "Free delivery for orders above 250 AED",
    "cart.total": "Total",
    "cart.currency": "AED",
    "cart.checkout": "Checkout",
    "cart.proceedToCheckout": "Proceed to Checkout",
    "cart.orderSummary": "Order Summary",
    "cart.minimumOrder": "Minimum order",
    "cart.minimumOrderTitle": "Minimum Order Not Met",
    "cart.minimumOrderDesc": "Minimum order amount is {amount} AED",
    "cart.minimumNotMet": "Minimum order not met",
    "cart.clearCart": "Clear Cart",
    "cart.secureCheckout": "Secure Checkout",
    "cart.freshGuarantee": "Freshness Guaranteed",
    "cart.inCart": "in cart",
    "cart.totalWeight": "Total Weight",
    "cart.notes": "Special Instructions",
    "cart.orderWhatsApp": "Order via WhatsApp",
    
    // Products
    "products.selectWeight": "Select Weight",
    "products.pricePerKg": "Price/KG",
    "products.total": "Total",
    "products.addToCart": "Add to Cart",
    "products.added": "Added",
    "products.notesPlaceholder": "Special instructions (cutting, marination, thickness...)",
    "products.notesHint": "Example: thin slices, lean cut, special seasoning",
    "products.quantity": "Quantity",
    "products.boxNotesPlaceholder": "Special box notes (e.g., no onions, extra sauce...)",
    
    // Checkout
    "checkout.title": "Checkout",
    "checkout.subtitle": "Complete your details to place your order",
    "checkout.backToCart": "Back to Cart",
    "checkout.customerInfo": "Customer Information",
    "checkout.name": "Full Name",
    "checkout.namePlaceholder": "Enter your full name",
    "checkout.phone": "Phone Number",
    "checkout.phonePlaceholder": "05xxxxxxxx",
    "checkout.email": "Email Address",
    "checkout.emailPlaceholder": "example@email.com",
    "checkout.deliveryAddress": "Delivery Address",
    "checkout.address": "Detailed Address",
    "checkout.addressPlaceholder": "Area, street, building number, apartment...",
    "checkout.city": "City",
    "checkout.cityNote": "Delivery is currently available in Abu Dhabi only",
    "checkout.notes": "Additional Notes",
    "checkout.notesPlaceholder": "Any special delivery instructions...",
    "checkout.paymentMethod": "Payment Method",
    "checkout.onlinePayment": "Online Payment",
    "checkout.onlinePaymentDesc": "Visa, MasterCard, Apple Pay",
    "checkout.cashOnDelivery": "Cash on Delivery",
    "checkout.codDesc": "Pay cash when you receive your order",
    "checkout.placeOrder": "Place Order",
    "checkout.payNow": "Pay Now",
    "checkout.processing": "Processing...",
    "checkout.orOrderVia": "Or order via",
    "checkout.orderWhatsApp": "Order via WhatsApp",
    "checkout.whatsappOrder": "Hello, I want to confirm my order:",
    "checkout.errorTitle": "Error",
    "checkout.fillRequired": "Please fill in all required fields",
    "checkout.successTitle": "Order Placed Successfully!",
    "checkout.codSuccess": "Thank you! We will contact you shortly to confirm your order",
    "checkout.processingPayment": "Processing Payment",
    "checkout.redirecting": "Redirecting to payment page...",
    "checkout.emptyCart": "Cart is Empty",
    "checkout.emptyCartDesc": "Add products to your cart to continue",
    "checkout.comingSoon": "Online Ordering Coming Soon",
    "checkout.comingSoonDesc": "We're setting up online payments and delivery. For now, order via WhatsApp!",
    "checkout.comingSoonButton": "Coming Soon...",
    "checkout.iikoStatus": "iiko POS Integration in Progress",
    "checkout.iikoStatusReady": "✓ iiko POS Ready - Fail-Safe Enabled",
    "checkout.codActive": "Cash on Delivery Available",
    "checkout.codActiveDesc": "Order now and pay cash when you receive your order!",
    "checkout.orderError": "An error occurred while placing your order. Please try again.",
    "checkout.invalidPhone": "Please enter a valid phone number (e.g., 0501234567)",
    
    // Order Success
    "orderSuccess.title": "Order Received!",
    "orderSuccess.description": "Thank you! Your order has been received and we will contact you shortly to confirm details and delivery.",
    "orderSuccess.whatNext": "What's Next?",
    "orderSuccess.whatNextDesc": "Our team will contact you within an hour to confirm your order and delivery time.",
    "orderSuccess.backHome": "Back to Home",
    "orderSuccess.continueShopping": "Continue Shopping",
    "orderSuccess.needHelp": "Need Help?",
    "orderSuccess.contactUs": "Contact us via WhatsApp",
    
    // Footer
    "footer.description": "We provide the finest fresh halal meats, committed to the highest standards of quality and hygiene. Over 14 years of experience serving our customers.",
    "footer.quickLinks": "Quick Links",
    "footer.shopCategories": "Shop Categories",
    "footer.contactUs": "Contact Us",
    "footer.followUs": "Follow Us",
    "footer.rights": "All Rights Reserved",
    
    // Recipes
    "recipes.tagline": "Recipes",
    "recipes.title": "Al Saraya Recipes",
    "recipes.description": "Professional recipes from Al Saraya chefs — learn the best ways to prepare grilled dishes using our fresh meats",
    "recipes.readRecipe": "Read Recipe",
    "recipes.allRecipes": "All Recipes",
    "recipes.minutes": "minutes",
    "recipes.people": "people",
    "recipes.difficulty.easy": "Easy",
    "recipes.difficulty.medium": "Medium",
    "recipes.difficulty.hard": "Hard",
    "recipes.introduction": "Introduction",
    "recipes.recommendedCut": "Recommended Cut",
    "recipes.ingredients": "Ingredients",
    "recipes.chefTips": "Chef Tips",
    "recipes.preparationMethod": "Preparation Method",
    "recipes.readyToPrepare": "Ready to prepare this recipe?",
    "recipes.orderIngredientsMessage": "Order fresh ingredients from Al Saraya Butchery and enjoy the best results",
    "recipes.notFound": "Recipe Not Found",
    "recipes.notFoundDesc": "Sorry, we couldn't find this recipe",
    "recipes.discoverRecipes": "Discover Our Recipes",
    "recipes.discoverDescription": "Professional recipes from Al Saraya chefs for preparing delicious dishes",
    
    // Recipe Items
    "recipe.lambRibs.title": "Charcoal Grilled Lamb Ribs",
    "recipe.lambRibs.desc": "Charcoal grilled lamb ribs recipe with authentic Arabic marinade for gatherings",
    "recipe.shishTaouk.title": "Levantine Shish Taouk",
    "recipe.shishTaouk.desc": "Shish taouk Levantine style with yogurt and Arabic spice marinade",
    "recipe.kebab.title": "Levantine Style Meat Kebab",
    "recipe.kebab.desc": "Authentic Aleppo kebab with Arabic spices and onion - premium restaurant recipe",
    
    // Menu Section & Page
    "menu.tagline": "Our Menu",
    "menu.title": "Al Saraya Grill Menu",
    "menu.description": "Fresh grilled dishes prepared daily using our selected meats, with authentic Levantine seasoning and unforgettable taste.",
    "menu.popular": "Most Popular",
    "menu.viewFullMenu": "View Full Menu",
    "menu.currency": "AED",
    "menu.readyToOrder": "Ready to Order?",
    "menu.orderNowMessage": "Order now via WhatsApp and enjoy the most delicious authentic Levantine grills",
    "menu.grills": "Grills",
    "menu.appetizers": "Appetizers",
    "menu.steaks": "Steaks",
    "menu.mainDishes": "Main Dishes",
    "menu.salads": "Salads",
    "menu.beverages": "Beverages",
    
    // Menu Items
    "menu.mixedGrill.name": "Al Saraya Mixed Grill",
    "menu.mixedGrill.desc": "Premium selection of kebab, shaqf, and ribs with grilled vegetables",
    "menu.lambRibs.name": "Grilled Lamb Ribs",
    "menu.lambRibs.desc": "Tender lamb ribs marinated with Al Saraya special blend",
    "menu.beefKebab.name": "Beef Kebab",
    "menu.beefKebab.desc": "Fresh beef kebab with authentic Levantine spices",
    "menu.shaqf.name": "Shaqf Meat",
    "menu.shaqf.desc": "Charcoal grilled meat pieces with tomatoes and peppers",
    "menu.herbChicken.name": "Herb Grilled Chicken",
    "menu.herbChicken.desc": "Half chicken grilled with Mediterranean herbs",
    "menu.filletSteak.name": "Fillet Steak",
    "menu.filletSteak.desc": "Grilled fillet steak cooked to your preference",
    
    // Trust Badges
    "trust.halal": "100% Halal",
    "trust.halalDesc": "Slaughtered according to Islamic law",
    "trust.quality": "Premium Quality",
    "trust.qualityDesc": "Finest meat cuts",
    "trust.delivery": "Fast Delivery",
    "trust.deliveryDesc": "To your doorstep",
    "trust.fresh": "Fresh Daily",
    "trust.freshDesc": "Fresh meats every day",
    "trust.experience": "6+ Years Experience",
    "trust.experienceDesc": "Experience ensures quality",
    "trust.customers": "10,000+ Customers",
    "trust.customersDesc": "Happy customers",
    
    // Delivery Section
    "delivery.service": "Delivery Service",
    "delivery.title": "Fresh Meats to Your Doorstep",
    "delivery.description": "We deliver the finest fresh halal meats as fast as possible. Order now and enjoy unmatched quality.",
    "delivery.fast": "Fast Delivery",
    "delivery.fastDesc": "Within a few hours",
    "delivery.coverage": "Wide Coverage",
    "delivery.coverageDesc": "Abu Dhabi, Al Ain and surrounding areas",
    
    // Why Choose Us Section
    "whyChoose.title": "Why Al Saraya?",
    "whyChoose.subtitle": "Unmatched quality and unforgettable trust",
    "whyChoose.fresh.title": "Fresh Meat Daily",
    "whyChoose.fresh.desc": "We select the finest fresh meat daily from trusted sources",
    "whyChoose.cutting.title": "Professional Custom Cutting",
    "whyChoose.cutting.desc": "Expert team cuts meat to your exact specifications",
    "whyChoose.hygiene.title": "Strict Hygiene Standards",
    "whyChoose.hygiene.desc": "We maintain the highest hygiene and quality standards",
    "whyChoose.trust.title": "Trusted Since 2019",
    "whyChoose.trust.desc": "Over 6 years of experience serving thousands of customers",
    
    // Best Sellers Section
    "bestSellers.tagline": "Most Popular",
    "bestSellers.title": "Our Best Sellers 🔥",
    "bestSellers.viewAll": "View All Products",
    "bestSellers.orderNow": "Order Now",
    "bestSellers.perKg": "/kg",
    
    // How To Order Section
    "howToOrder.title": "Order in 4 Simple Steps 👌",
    "howToOrder.subtitle": "No hassle – No waiting – Guaranteed quality 🥩",
    "howToOrder.step1.title": "Choose Your Meat",
    "howToOrder.step1.desc": "Browse our fresh meat selection and pick what suits you",
    "howToOrder.step2.title": "Select Cut & Quantity",
    "howToOrder.step2.desc": "Choose your cutting style and quantity as needed",
    "howToOrder.step3.title": "Order Online or WhatsApp",
    "howToOrder.step3.desc": "Order easily from the website or directly via WhatsApp",
    "howToOrder.step4.title": "Receive Fresh Meat",
    "howToOrder.step4.desc": "We prepare your order carefully and deliver to your doorstep",
    "howToOrder.trustMessage": "Daily orders from thousands of happy customers",
    
    // Trust Stats Section
    "trustStats.title": "Trusted by Thousands",
    "trustStats.subtitle": "Numbers that speak for our quality",
    "trustStats.customers": "Happy Customers",
    "trustStats.rating": "Customer Rating",
    "trustStats.years": "Years Experience",
    "trustStats.halal": "Halal Certified",
    
    // Final CTA Section
    "finalCTA.title": "Ready to Order Fresh Meat Today?",
    "finalCTA.subtitle": "Make the right choice and stay confident",
    "finalCTA.whatsapp": "Order via WhatsApp",
    "finalCTA.order": "Order Now",
    "finalCTA.trust": "🥩 100% Fresh Halal Meat • Fast Delivery • Secure Payment",
    
    // Delivery & Payment Section
    "deliveryPayment.title": "Delivery & Payment",
    "deliveryPayment.subtitle": "Fast delivery – Secure payment – Comfortable experience from first order",
    "deliveryPayment.fast.title": "Fast Delivery",
    "deliveryPayment.fast.desc": "Delivery across UAE areas",
    "deliveryPayment.sameDay.title": "Same-Day Preparation",
    "deliveryPayment.sameDay.desc": "We prepare your order fresh",
    "deliveryPayment.secure.title": "Secure Payment",
    "deliveryPayment.secure.desc": "100% encrypted transactions",
    "deliveryPayment.cod.title": "Cash on Delivery",
    "deliveryPayment.cod.desc": "Available for your convenience",
    "deliveryPayment.methods": "Accepted Payment Methods",
    "deliveryPayment.poweredBy": "Powered by Network International",
    
    // Saraya Boxes Section
    "sarayaBoxes.tagline": "Special Offers",
    "sarayaBoxes.title": "Special Boxes",
    "sarayaBoxes.subtitle": "Complete boxes ready for BBQ and parties - everything you need in one box",
    "sarayaBoxes.trending": "Trending",
    "sarayaBoxes.bestSeller": "Best Seller",
    "sarayaBoxes.orderWhatsapp": "Order Now via WhatsApp",
    "sarayaBoxes.currency": "AED",
    "sarayaBoxes.comingSoon": "More boxes coming soon...",
    "sarayaBoxes.viewAll": "View All Boxes",
    
    // WhatsApp CTA
    "whatsapp.orderNow": "Order Now!",
    "whatsapp.getFreshMeat": "Get Fresh Meat Today",
    "whatsapp.contactVia": "Contact via WhatsApp",
    "whatsapp.fastDelivery": "Fast Delivery",
    "whatsapp.freshDaily": "Fresh Daily",
    "whatsapp.halal100": "100% Halal",
    "whatsapp.defaultMessage": "Hello, I would like to order fresh meat",
    
    // Order Tracking
    "tracking.title": "Track Your Order",
    "tracking.subtitle": "Follow your order status and driver location in real-time",
    "tracking.searchPlaceholder": "Enter order number",
    "tracking.search": "Search",
    "tracking.orderNotFound": "Order Not Found",
    "tracking.orderNotFoundDesc": "We could not find an order with this number",
    "tracking.tryAgain": "Try Again",
    "tracking.startDemo": "Start Demo",
    "tracking.demoMode": "Demo Mode",
    "tracking.comingSoon": "Tracking System Under Development",
    "tracking.comingSoonDesc": "We are working on activating live tracking",
    "tracking.liveTracking": "Live Driver Tracking",
    "tracking.deliveryLocation": "Delivery Location",
    "tracking.estimatedArrival": "Estimated Arrival",
    "tracking.needHelp": "Need Help?",
    "tracking.callUs": "Call Us",
    "tracking.backToHome": "Back to Home",
    
    // Driver Panel
    "driver.title": "Driver Panel",
    "driver.subtitle": "Manage deliveries and location tracking",
    "driver.currentOrder": "Current Order",
    "driver.orderNumber": "Order Number",
    "driver.deliveryAddress": "Delivery Address",
    "driver.locationTracking": "Location Tracking",
    "driver.sharingLocation": "Sharing Location",
    "driver.trackingOff": "Tracking Off",
    "driver.start": "Start",
    "driver.stop": "Stop",
    "driver.deliveryActions": "Delivery Actions",
    "driver.startDelivery": "Start Delivery",
    "driver.markDelivered": "Mark as Delivered",
    "driver.deliveredSuccess": "Delivered Successfully!",
    "driver.callCustomer": "Call Customer",
    "driver.openInMaps": "Open in Maps",
    "driver.noOrders": "No Orders Assigned",
    "driver.noOrdersDesc": "You have no orders assigned currently",
    
    // Admin Dashboard
    "admin.title": "Delivery Dashboard",
    "admin.subtitle": "Manage orders and drivers",
    "admin.pendingOrders": "Pending Orders",
    "admin.activeDeliveries": "Active Deliveries",
    "admin.availableDrivers": "Available Drivers",
    "admin.deliveredToday": "Delivered Today",
    "admin.allOrders": "All Orders",
    "admin.refresh": "Refresh",
    "admin.assignDriver": "Assign Driver",
    "admin.noDriversAvailable": "No drivers available",
    "admin.driverManagement": "Driver Management",
    "admin.activeDrivers": "Active Drivers",
    "admin.panel": "Admin Panel",
    "admin.products": "Products",
    "admin.productsManagement": "Products Management",
    "admin.addProduct": "Add Product",
    "admin.editProduct": "Edit Product",
    "admin.deleteProduct": "Delete Product",
    "admin.orders": "Orders",
    "admin.ordersManagement": "Orders Management",
    "admin.orderNumber": "Order Number",
    "admin.customer": "Customer",
    "admin.status": "Status",
    "admin.total": "Total",
    "admin.date": "Date",
    "admin.actions": "Actions",
    "admin.settings": "Settings",
    "admin.deliverySettings": "Delivery Settings",
    "admin.deliveryZones": "Delivery Zones",
    "admin.addZone": "Add Zone",
    "admin.deleteZone": "Delete Zone",
    "admin.deliveryFee": "Delivery Fee",
    "admin.freeDeliveryThreshold": "Free Delivery Threshold",
    "admin.estimatedTime": "Estimated Delivery Time",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.confirm": "Confirm",
    "admin.error": "Error",
    "admin.success": "Success",
    "admin.loading": "Loading...",
    "admin.noData": "No data available",
    "admin.search": "Search",
    "admin.filter": "Filter",
    "admin.export": "Export",
    "admin.import": "Import",
    "admin.image": "Image",
    "admin.name": "Name",
    "admin.price": "Price",
    "admin.category": "Category",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.view": "View",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.chooseImage": "Choose Image",
    "admin.uploading": "Uploading...",
    "admin.uploadSuccess": "Image uploaded successfully",
    "admin.uploadError": "Error uploading image",
    
    // Sticky CTA
    "stickyCTA.title": "Ready to Order?",
    "stickyCTA.subtitle": "Fresh meat delivered to your door",
    "stickyCTA.button": "Order Now",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "ar";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.setAttribute("dir", language === "ar" ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "ar" ? "en" : "ar"));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
