-- Fix: Remove order_number from RLS check since it's auto-generated by trigger
-- Drop existing anonymous insert policy
DROP POLICY IF EXISTS "Anonymous can create orders" ON public.orders;
DROP POLICY IF EXISTS "Authenticated users can create orders" ON public.orders;

-- Create new INSERT policy without order_number requirement
-- The trigger will auto-generate order_number before insert
CREATE POLICY "Anyone can create orders" 
ON public.orders 
FOR INSERT 
WITH CHECK (
  customer_name IS NOT NULL 
  AND customer_phone IS NOT NULL 
  AND delivery_address IS NOT NULL 
  AND items IS NOT NULL 
  AND total >= 0
);